name: Build and Lint and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [10, 12]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install project
        run: npm ci
      - name: Lint the project
        run: npx lint-staged
      - name: Build the project
        run: npm run build --if-present
      # - name: Run tests # Without tests, sorry
      #   run: npm run test:ci